### ISSUE TITLE
Many Bugs

### ISSUE THREAD

**Issue by KNJOrlx** [Zipper213/LoyaltyMCIssues#10]
Factions > You are allowed to select any kit unlimited times including the ranked ones. Also lets you sell the items from the kits so you can also get unlimited money. Also, you can place and break just a few blocks away from the general spawn area (I don't know if this is intended). Also, you can use commands while in combat...
Skyblock > None of the commands for Skyblock work, and some slappers disappear then re-appear when you hit them.
Thanks,
 KN JOrlx

P.S. I am from the staff team, I am a manager.

**Comment by WesleyVanNeck** [comment]
The slapper disappear yes that's a bug I can't fix 

Kits yes I know that I need removed op from the command

Commands In combat are intentionally 

Skyblock command are broken because plugin break

**Comment by WesleyVanNeck** [comment]
@KNJOrlx those are know some I can't fix do some I do I said earlier about the npcs that's problem  and I unable to fix the rest is fixable

**Comment by WesleyVanNeck** [comment]
Btw you rever to them as slappers but it's not slapper plugin it's called citzens2

**Comment by WesleyVanNeck** [comment]
Selling the kits can't be fixed because  it is not freaking pocketmine (pmmp) so deal with it 🤬😡😠 same if say slapper it isn't slapper

**Comment by WesleyVanNeck** [comment]
@Zipper213 close this

**Comment by WesleyVanNeck** [comment]
both commands of kit and block breaking is on your rank so thats not bug the npc flickering cant be fixed

the rest is fixed now

**Comment by WesleyVanNeck** [comment]
![unknown](https://user-images.githubusercontent.com/25864932/58891246-741d6c80-86ec-11e9-81e8-4d1543b1fbb7.png)

npc flikering is fixe do a seen above thre is packet broke so for now hover over th npc to get the name i will make seccond issue about that

**Comment by Zipper213** [comment]
I will be closing this.  You may DMme if any more problems occur related to this issue.  ZippyTheDoggy#9276
