### ISSUE TITLE
new npc dont show there namtag

### ISSUE THREAD

**Issue by WesleyVanNeck** [Zipper213/LoyaltyMCIssues#11]
workaround:  hover over them to see the nametag

**Comment by WesleyVanNeck** [comment]
![unknown](https://user-images.githubusercontent.com/25864932/58891495-e726e300-86ec-11e9-867f-4aa72990877c.png)

this is because the status packat is broken

**Comment by Zipper213** [comment]
@WesleyVanNeck 

I suggest adding a plugin that allows you to make floating text in the sky, like Holograms plugin, for example.  

I will not close this issue until further reply.

**Comment by Zipper213** [comment]
Closing issue because there was no reply for 100 years.
